### ISSUE TITLE
Mettre à jour depuis Contact Form 7 > 5.3.2 - Faille de sécurité sur les téléversements de fichier

### ISSUE THREAD

**Issue by audrasjb** [Tanaguru/contact-form-7-tanaguru#11]
Bonjour,

Je ne suis pas utilisateur de l'extension, mais elle a été présentée récemment sur un canal WP en français et du coup j'ouvre cette issue pour vous conseiller d'effectuer un merge de Contact Form 7 pour corriger la dernière faille de sécurité concernant le téléversement de fichiers.

Plus de détails ici : https://wpscan.com/vulnerability/7391118e-eef5-4ff8-a8ea-f6b65f442c63

Merci et bonne journée à toutes et à tous,
Jb

**Comment by ghost** [comment]
Bonjour,

Merci beaucoup pour le signalement. Il était prévu de mettre à jour ce fork prochainement de toutes façons mais voilà une excellente raison complémentaire. Je m'en occupe dans les prochains jours.

Bonne journée

**Comment by ghost** [comment]
Corrigé via un nouveau (vrai) fork. Nouvelle release disponible ici : https://github.com/Tanaguru/contact-form-7/releases
